# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GSLoopCPP <- function(nIt, nBurnIn, nC, Y, XFE, XRE, XL, U, ZRE, beta, sig2, WRE, muClus, SigmaClus, WLat, gammaLat, a, b, lambdaFE, PhiRE, etaRE, lam0, mu0, nu0, Psi0, PhiLat, etaLat, scale, shape) {
    .Call(`_ProfileGLMM_GSLoopCPP`, nIt, nBurnIn, nC, Y, XFE, XRE, XL, U, ZRE, beta, sig2, WRE, muClus, SigmaClus, WLat, gammaLat, a, b, lambdaFE, PhiRE, etaRE, lam0, mu0, nu0, Psi0, PhiLat, etaLat, scale, shape)
}

